### ISSUE TITLE
Error:Could not find io.fabianterhorst:iron-annotations:0.1.

### ISSUE THREAD

**Issue by mradzinski** [FabianTerhorst/Iron#2]
Gradle does not sync, seems to fail finding dependencies:

```
Error: Could not find io.fabianterhorst:iron-annotations:0.1.
Required by:
    mobile:vault:unspecified
    mobile:vault:unspecified > io.fabianterhorst:iron-compiler:0.2
```

Gradle dependencies looking like:

    compile 'io.fabianterhorst:iron:0.4'
    compile 'io.fabianterhorst:iron-annotations:0.1'
    compile 'io.fabianterhorst:iron-encryption:0.1'
    apt 'io.fabianterhorst:iron-compiler:0.2'

**Comment by FabianTerhorst** [comment]
have you added 
```allprojects {
    repositories {
        jcenter()
    }
}```

in your project gradle file?

**Comment by mradzinski** [comment]
Yep,

```
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
        ...
    }
}
```

**Comment by mradzinski** [comment]
It might be that the dependencies are not yet resolvable through JCenter. Sometimes dependencies takes a while to replicate and I just checked and it seems you uploaded them today. I'll try again syncing in a couple of hours and I'll let you know of the outcome, let's leave this open meanwhile.

**Comment by FabianTerhorst** [comment]
i have requested a linking to jcenter at bintray.com, looks like annotations wasn´t linked.

**Comment by FabianTerhorst** [comment]
encryption wasn´t linked too. Should be done by bintray in the next hours. 

compile 'io.fabianterhorst:iron:0.5'
compile 'io.fabianterhorst:iron-retrofit:0.3'
compile 'io.fabianterhorst:iron-annotations:0.1'
compile 'io.fabianterhorst:iron-encryption:0.2'
apt 'io.fabianterhorst:iron-compiler:0.2'

**Comment by FabianTerhorst** [comment]
There should be published on jcenter. Bintry approved the linking.
