### ISSUE TITLE
Field types that have no empty constructor will fail to compile

### ISSUE THREAD

**Issue by mradzinski** [FabianTerhorst/Iron#3]
Try defining a field of type *Long* inside a *@Store* model. It will fail to compile due to the fact that *java.lang.Long* has no empty constructor

```
    public static java.lang.Long getTest() {
        return Iron.chest().read("test", new java.lang.Long()); // Long has no empty constructor
    }
```

May I recommend checking for the field type and acting accordingly? So, if String then *new java.lang.String()* will work, but if *Long, Boolean, Byte, etc* then the default value should be *0, false, etc* (or just always return null, I mean, a null-check is pretty much common)

**Comment by FabianTerhorst** [comment]
Thanks for your testing. I will take a look inside this and i think giving the annotation a default value would be a good way.

**Comment by FabianTerhorst** [comment]
If no default value is provided with the annotation it should return null.

**Comment by mradzinski** [comment]
Absolutely, that should do the trick

**Comment by FabianTerhorst** [comment]
compile 'io.fabianterhorst:iron-annotations:0.2'
apt 'io.fabianterhorst:iron-compiler:0.4.0'
```@Store
public class Main {
    @DefaultObject
    @Name(value = "contributors", transaction = true, listener = true, loader = true, async = true)
    ArrayList<Contributor> contributors;

    @DefaultObject
    @Name("repos")
    ArrayList<Contributor> repos;

    @Name("my_username")
    String userName;

    @DefaultLong(120)
    Long bla;
}
```

**Comment by FabianTerhorst** [comment]
edit:apt 'io.fabianterhorst:iron-compiler:0.4'
