### ISSUE TITLE
Conflicted dependecy

### ISSUE THREAD

**Issue by rafakob** [FabianTerhorst/Iron#5]
I've added Iron to Gradle and sync is failing:
```
Error:Conflict with dependency 'org.ow2.asm:asm'. Resolved versions for app (5.0.3) and test app (5.0.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
```

I can fix that with this:
```
compile ('io.fabianterhorst:iron:0.7.2'){
        exclude group: 'org.ow2.asm', module: 'asm'
    }
```

but would it be possilbe to change this somehow on your side?

**Comment by rafakob** [comment]
One more thing. Before adding Iron I have method count:
```
Total methods: 50330 (76,80% used)
Total fields in:  53068 (80,98% used)
```

After adding Iron this limit exceeds. Should I exclude something? I think you need to redesign your modules and gradles.

**Comment by rafakob** [comment]
Nvm, resloved with this:
```
    compile('io.fabianterhorst:iron:0.7.2') {
        exclude module: 'asm'
        exclude module: 'objenesis'
    }
```

**Comment by FabianTerhorst** [comment]
@rafakob what test dependencies are you using, maybe there have other versions. There shouldn´t influence the methodcount at all and when you are using proguard the methodcount isn´t noticable.

**Comment by FabianTerhorst** [comment]
@rafakob org.ow2.asm:asm:5.0.3 and org.objenesis:objenesis:2.1 are dependencies from kryo.
