### ISSUE TITLE
ConcurrentModificationException for callbacks

### ISSUE THREAD

**Issue by pivotal-graham-bell** [FabianTerhorst/Iron#6]
Under highly concurrent situations, one thread will be trying to iterate callback listeners inside *Chest.callCallbacks()* while another is calling *Chest.removeListener()*. This can produce exceptions such as:

```java
Caused by: java.util.ConcurrentModificationException
  at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
  at io.fabianterhorst.iron.Chest.removeListener(Chest.java:406)
  at io.fabianterhorst.iron.Chest$3$2.call(Chest.java:168)
  at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:71)
  at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
  at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
  at rx.Subscriber.unsubscribe(Subscriber.java:98)
```

Looking into the source code for Chest.java, it appears the problem may be due to the fact *Chest.callCallbacks()* synchronizes on *mCallbacks*, while other methods like *Chest.addOnDataChangeListener()* and *Chest.removeListener()* have their methods synchronized. As such these they are synchronizing on different monitors, which is why ConcurrentModificationExceptions occur.

**Comment by FabianTerhorst** [comment]
Can you write a test that is reproducing this issue. Check out the other tests for this: https://github.com/FabianTerhorst/Iron/blob/master/iron/src/androidTest/java/io/fabianterhorst/iron/multithread/MultiThreadTest.java

**Comment by pivotal-graham-bell** [comment]
I've forked the repo and created a test (somewhat similar to MultiThreadTest.java) that triggers the ConcurrentModificationException. The commit is here: https://github.com/pivotal-graham-bell/Iron/commit/1e6c3787e40b45566d88617e61c49ed9cb709679

I've also added what I think would be a sufficient fix for the bug here: https://github.com/pivotal-graham-bell/Iron/commit/af68601640867e92f15364695309bb13a23061ac

**Comment by FabianTerhorst** [comment]
When the test is working with the commit you can create a pull request for this as well.

**Comment by FabianTerhorst** [comment]
Release 0.8.0 is fixing this.
